# disable touchpad
# ⎜   ↳ PS/2 Generic Mouse                        id=11   [slave  pointer  (2)]
# TODO
# xinput disable 10

[ -d ~/.xinitrc.d ] && for f in ~/.xinitrc.d/* ; do source $f ; done

# exec /usr/bin/fvwm
exec /usr/bin/startkde
